// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApEouCWfs6I191iY1_HO7Bp8a2m0osarg',
    appId: '1:908677582509:web:5c8bef0cd76aa222ce4024',
    messagingSenderId: '908677582509',
    projectId: 'flutter-chat-app65464',
    authDomain: 'flutter-chat-app65464.firebaseapp.com',
    storageBucket: 'flutter-chat-app65464.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDknvLhaY5gC8nOgjE7qxaQOQBLrjLV_Os',
    appId: '1:908677582509:android:3bb840602d3ec640ce4024',
    messagingSenderId: '908677582509',
    projectId: 'flutter-chat-app65464',
    storageBucket: 'flutter-chat-app65464.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWhJwwMlkcrpsipLtwsZDD0TDZTb0u99A',
    appId: '1:908677582509:ios:74f602cdc3bb7169ce4024',
    messagingSenderId: '908677582509',
    projectId: 'flutter-chat-app65464',
    storageBucket: 'flutter-chat-app65464.appspot.com',
    iosClientId: '908677582509-ue2oeme8epsn09p40ac9e3dujco32p2l.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
